import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"
import Navbar from "../Components/Navbar";
import ContextLayout from "../context/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <ContextLayout>
            {children}
          </ContextLayout>
      </body>
    </html>
  );
}
